version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spellcaster
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/usr/local/var/postgresql@14
  web:
    build: .
    environment:
      DB_CONNECTION_STRING: "host=db user=postgres password=password dbname=postgres sslmode=disable"
    ports:
      - "8000:8080"
    depends_on:
      - db
    volumes:
      - ./:/app/
volumes:
  pgdata:
