name: Push to registry

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up DOCTL
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to registry
        run: |
          doctl registry login

      - name: Push to registry
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: registry.digitalocean.com/spellcaster:latest
          file: ./backend/Dockerfile
