name: Push to registry

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to registry
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: registry.digitalocean.com/spellcaster:latest
          file: ./backend/Dockerfile
